export const COUNTRIES_ISO = [
    { name: "Islas Åland", code: "AX" },
    { name: "Albania", code: "AL" },
    { name: "Argelia", code: "DZ" },
    { name: "Samoa Americana", code: "AS" },
    { name: "Andorra", code: "AD" },
    { name: "Angola", code: "AO" },
    { name: "Anguila", code: "AI" },
    { name: "Antigua y Barbuda", code: "AG" },
    { name: "Argentina", code: "AR" },
    { name: "Armenia", code: "AM" },
    { name: "Aruba", code: "AW" },
    { name: "Australia", code: "AU" },
    { name: "Austria", code: "AT" },
    { name: "Azerbaiyán", code: "AZ" },
    { name: "Bahamas", code: "BS" },
    { name: "Baréin", code: "BH" },
    { name: "Bangladesh", code: "BD" },
    { name: "Barbados", code: "BB" },
    { name: "Bielorrusia", code: "BY" },
    { name: "Bélgica", code: "BE" },
    { name: "Belice", code: "BZ" },
    { name: "Benín", code: "BJ" },
    { name: "Bermudas", code: "BM" },
    { name: "Bután", code: "BT" },
    { name: "Bolivia", code: "BO" },
    { name: "Bonaire, San Eustaquio y Saba", code: "BQ" },
    { name: "Bosnia y Herzegovina", code: "BA" },
    { name: "Botsuana", code: "BW" },
    { name: "Brasil", code: "BR" },
    { name: "Brunéi Darussalam", code: "BN" },
    { name: "Bulgaria", code: "BG" },
    { name: "Burkina Faso", code: "BF" },
    { name: "Burundi", code: "BI" },
    { name: "Camboya", code: "KH" },
    { name: "Camerún", code: "CM" },
    { name: "Canadá", code: "CA" },
    { name: "Islas Canarias, España", code: "IC" },
    { name: "Cabo Verde", code: "CV" },
    { name: "Islas Caimán", code: "KY" },
    { name: "República Centroafricana", code: "CF" },
    { name: "Chad", code: "TD" },
    { name: "Chile", code: "CL" },
    { name: "China, República Popular de", code: "CN" },
    { name: "Colombia", code: "CO" },
    { name: "Comoras", code: "KM" },
    { name: "Congo", code: "CG" },
    { name: "Islas Cook", code: "CK" },
    { name: "Costa Rica", code: "CR" },
    { name: "Croacia", code: "HR" },
    { name: "Curazao", code: "CW" },
    { name: "Chipre", code: "CY" },
    { name: "República Checa", code: "CZ" },
    { name: "Dinamarca", code: "DK" },
    { name: "Yibuti", code: "DJ" },
    { name: "Dominica", code: "DM" },
    { name: "República Dominicana", code: "DO" },
    { name: "Ecuador", code: "EC" },
    { name: "Egipto", code: "EG" },
    { name: "El Salvador", code: "SV" },
    { name: "Guinea Ecuatorial", code: "GQ" },
    { name: "Eritrea", code: "ER" },
    { name: "Estonia", code: "EE" },
    { name: "Etiopía", code: "ET" },
    { name: "Islas Malvinas (Falkland)", code: "FK" },
    { name: "Islas Feroe (Dinamarca)", code: "FO" },
    { name: "Fiyi", code: "FJ" },
    { name: "Finlandia", code: "FI" },
    { name: "Francia", code: "FR" },
    { name: "Guayana Francesa", code: "GF" },
    { name: "Polinesia Francesa (Tahití)", code: "PF" },
    { name: "Territorios Australes Franceses", code: "TF" },
    { name: "Gabón", code: "GA" },
    { name: "Gambia", code: "GM" },
    { name: "Georgia", code: "GE" },
    { name: "Alemania", code: "DE" },
    { name: "Ghana", code: "GH" },
    { name: "Gibraltar", code: "GI" },
    { name: "Grecia", code: "GR" },
    { name: "Groenlandia (Dinamarca)", code: "GL" },
    { name: "Granada", code: "GD" },
    { name: "Guadalupe", code: "GP" },
    { name: "Guam", code: "GU" },
    { name: "Guatemala", code: "GT" },
    { name: "Guernsey", code: "GG" },
    { name: "Guinea", code: "GN" },
    { name: "Guinea-Bissau", code: "GW" },
    { name: "Guyana", code: "GY" },
    { name: "Haití", code: "HT" },
    { name: "Islas Heard y McDonald", code: "HM" },
    { name: "Honduras", code: "HN" },
    { name: "Hong Kong", code: "HK" },
    { name: "Hungría", code: "HU" },
    { name: "Islandia", code: "IS" },
    { name: "India", code: "IN" },
    { name: "Indonesia", code: "ID" },
    { name: "Irak", code: "IQ" },
    { name: "Irlanda", code: "IE" },
    { name: "Isla de Man", code: "IM" },
    { name: "Israel", code: "IL" },
    { name: "Italia", code: "IT" },
    { name: "Costa de Marfil", code: "CI" },
    { name: "Jamaica", code: "JM" },
    { name: "Japón", code: "JP" },
    { name: "Jersey", code: "JE" },
    { name: "Jordania", code: "JO" },
    { name: "Kazajistán", code: "KZ" },
    { name: "Kenia", code: "KE" },
    { name: "Kiribati", code: "KI" },
    { name: "Corea, República de", code: "KR" },
    { name: "Kuwait", code: "KW" },
    { name: "Kirguistán", code: "KG" },
    { name: "Laos", code: "LA" },
    { name: "Letonia", code: "LV" },
    { name: "Líbano", code: "LB" },
    { name: "Lesoto", code: "LS" },
    { name: "Liberia", code: "LR" },
    { name: "Liechtenstein", code: "LI" },
    { name: "Lituania", code: "LT" },
    { name: "Luxemburgo", code: "LU" },
    { name: "Macao", code: "MO" },
    { name: "Macedonia", code: "MK" },
    { name: "Madagascar", code: "MG" },
    { name: "Malaui", code: "MW" },
    { name: "Malasia", code: "MY" },
    { name: "Maldivas", code: "MV" },
    { name: "Malí", code: "ML" },
    { name: "Malta", code: "MT" },
    { name: "Islas Marshall", code: "MH" },
    { name: "Martinica", code: "MQ" },
    { name: "Mauritania", code: "MR" },
    { name: "Mauricio", code: "MU" },
    { name: "Mayotte", code: "YT" },
    { name: "México", code: "MX" },
    { name: "Micronesia, Estados Federados de", code: "FM" },
    { name: "Moldavia", code: "MD" },
    { name: "Mónaco", code: "MC" },
    { name: "Mongolia", code: "MN" },
    { name: "Montenegro", code: "ME" },
    { name: "Montserrat", code: "MS" },
    { name: "Marruecos", code: "MA" },
    { name: "Mozambique", code: "MZ" },
    { name: "Myanmar", code: "MM" },
    { name: "Namibia", code: "NA" },
    { name: "Nauru, República de", code: "NR" },
    { name: "Nepal", code: "NP" },
    { name: "Países Bajos", code: "NL" },
    { name: "Nueva Caledonia", code: "NC" },
    { name: "Nueva Zelanda", code: "NZ" },
    { name: "Nicaragua", code: "NI" },
    { name: "Níger", code: "NE" },
    { name: "Nigeria", code: "NG" },
    { name: "Isla Niue", code: "NU" },
    { name: "Isla Norfolk", code: "NF" },
    { name: "Islas Marianas del Norte", code: "MP" },
    { name: "Noruega", code: "NO" },
    { name: "Omán", code: "OM" },
    { name: "Pakistán", code: "PK" },
    { name: "Palaos", code: "PW" },
    { name: "Palestina", code: "PS" },
    { name: "Panamá", code: "PA" },
    { name: "Papúa Nueva Guinea", code: "PG" },
    { name: "Paraguay", code: "PY" },
    { name: "Perú", code: "PE" },
    { name: "Filipinas", code: "PH" },
    { name: "Pitcairn", code: "PN" },
    { name: "Polonia", code: "PL" },
    { name: "Portugal", code: "PT" },
    { name: "Puerto Rico", code: "PR" },
    { name: "Catar", code: "QA" },
    { name: "Reunión", code: "RE" },
    { name: "Rumania", code: "RO" },
    { name: "Rusia", code: "RU" },
    { name: "Ruanda", code: "RW" },
    { name: "Santa Elena", code: "SH" },
    { name: "San Pedro y Miquelón", code: "PM" },
    { name: "Samoa", code: "WS" },
    { name: "San Marino", code: "SM" },
    { name: "Santo Tomé y Príncipe", code: "ST" },
    { name: "Arabia Saudita", code: "SA" },
    { name: "Senegal", code: "SN" },
    { name: "Serbia", code: "RS" },
    { name: "Seychelles", code: "SC" },
    { name: "Sierra Leona", code: "SL" },
    { name: "Singapur", code: "SG" },
    { name: "Eslovaquia", code: "SK" },
    { name: "Eslovenia", code: "SI" },
    { name: "Islas Salomón", code: "SB" },
    { name: "Sudáfrica", code: "ZA" },
    { name: "Sudán del Sur", code: "SS" },
    { name: "España", code: "ES" },
    { name: "Sri Lanka", code: "LK" },
    { name: "San Bartolomé", code: "BL" },
    { name: "San Cristóbal y Nieves", code: "KN" },
    { name: "Santa Lucía", code: "LC" },
    { name: "San Martín", code: "MF" },
    { name: "San Vicente", code: "VC" },
    { name: "Sudán", code: "SD" },
    { name: "Surinam", code: "SR" },
    { name: "Svaldbard", code: "SJ" },
    { name: "Suazilandia", code: "SZ" },
    { name: "Suecia", code: "SE" },
    { name: "Suiza", code: "CH" },
    { name: "Taiwán", code: "TW" },
    { name: "Tayikistán", code: "TJ" },
    { name: "Tanzania", code: "TZ" },
    { name: "Tailandia", code: "TH" },
    { name: "Timor-Leste", code: "TL" },
    { name: "Togo", code: "TG" },
    { name: "Tokelau", code: "TK" },
    { name: "Tonga", code: "TO" },
    { name: "Trinidad y Tobago", code: "TT" },
    { name: "Túnez", code: "TN" },
    { name: "Turquía", code: "TR" },
    { name: "Turkmenistán", code: "TM" },
    { name: "Islas Turcas y Caicos", code: "TC" },
    { name: "Tuvalu", code: "TV" },
    { name: "Uganda", code: "UG" },
    { name: "Ucrania", code: "UA" },
    { name: "Emiratos Árabes Unidos", code: "AE" },
    { name: "Reino Unido", code: "GB" },
    { name: "Estados Unidos", code: "US" },
    { name: "Islas Ultramarinas Menores de Estados Unidos", code: "UM" },
    { name: "Uruguay", code: "UY" },
    { name: "Uzbekistán", code: "UZ" },
    { name: "Vanuatu", code: "VU" },
    { name: "Ciudad del Vaticano", code: "VA" },
    { name: "Venezuela", code: "VE" },
    { name: "Vietnam", code: "VN" },
    { name: "Islas Vírgenes (Británicas)", code: "VG" },
    { name: "Islas Vírgenes (EE.UU.)", code: "VI" },
    { name: "Wallis y Futuna", code: "WF" },
    { name: "Sahara Occidental", code: "EH" },
    { name: "Yemen", code: "YE" },
    { name: "Zambia", code: "ZM" },
    { name: "Zimbabue", code: "ZW" }
];
