'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'DE' | 'ES' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'ES',
  setLanguage: () => {},
  t: (key) => key,
});

const dictionary: Record<Language, Record<string, string>> = {
  ES: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.wallet': 'Mi Wallet',
    'nav.reservations': 'Reservas DiciCoin',
    'nav.marketplace': 'Marketplace',
    'nav.admin': 'Administración',
    'nav.logout': 'Cerrar Sesión',
    'nav.member': 'Miembro',
    'nav.administrator': 'Administrador',

    // Common Balance widget
    'balance.dp': 'DP',
    'balance.dc': 'DC',
    'balance.paid': 'Pagado',

    // Dashboard
    'dashboard.hello': 'Hola,',
    'dashboard.welcome': 'Bienvenido al centro financiero del ecosistema circular DiciCoin.',
    'dashboard.dp_title': 'Puntos de Actividad Dicilo',
    'dashboard.dp_desc': 'Acumulados por actividad en Dicilo.net',
    'dashboard.dc_title': 'DiciCoin Digital',
    'dashboard.dc_desc': '1 DC = 50 EUR de valor interno',
    'dashboard.dc_convert': 'Convertir DP',
    'dashboard.eur_title': 'Euros Pagados',
    'dashboard.eur_desc': 'Inversión total acumulada en monedas físicas',
    'dashboard.my_plans': 'Mi Plan de Pago de Monedas Físicas',
    'dashboard.no_plans': 'No tienes reservas activas de DiciCoin físicas.',
    'dashboard.no_plans_desc': 'Puedes reservar una moneda de colección con un pago inicial del 10%.',
    'dashboard.reserve_btn': 'Reservar DiciCoin Física',
    'dashboard.progress_prop': 'Progreso de propiedad',
    'dashboard.manage_payments': 'Gestionar Pagos',
    'dashboard.remaining_prefix': 'Faltan',
    'dashboard.remaining_suffix': 'para obtener el certificado físico',
    'dashboard.quick_actions': 'Acciones Rápidas',
    'dashboard.action_reserve': 'Reservar Nueva DiciCoin',
    'dashboard.action_convert': 'Convertir DP a DC',
    'dashboard.action_market': 'Mercado de Participaciones',
    'dashboard.legal_title': 'INFORMACIÓN LEGAL Y DE RIESGO',
    'dashboard.legal_text': 'DiciCoin es un activo físico coleccionable, crédito digital interno, acceso premium y participación exclusiva dentro del ecosistema digital cerrado Dicilo. No constituye en ningún caso una inversión financiera regulada ni garantizada. No se promete ningún tipo de rentabilidad económica futura, dividendos ni recompra obligatoria. Su valor radica en la exclusividad física y la utilidad de canje digital interna en Dicilo.net.',

    // Wallet
    'wallet.title': 'Mi Wallet Digital',
    'wallet.subtitle': 'Convierte tus puntos de Dicilo.net y revisa tu historial de movimientos.',
    'wallet.convert_card_title': 'Convertir DP a DiciCoin',
    'wallet.rule_desc': 'Regla del Ecosistema: 500 DP = 1 DC. Las conversiones son instantáneas y reversibles a través del soporte oficial. Las DiciCoins (DC) se valoran a 50 EUR interno para compras o canjes de beneficios.',
    'wallet.input_label': 'Puntos DP a Convertir',
    'wallet.available': 'Disponible',
    'wallet.placeholder': 'Múltiplos de 500 (e.g. 500, 1000)',
    'wallet.give': 'Entregas',
    'wallet.receive': 'Recibes',
    'wallet.btn_submit': 'Convertir a DiciCoin (DC)',
    'wallet.btn_submit_loading': 'Procesando conversión...',
    'wallet.history_title': 'Historial de Transacciones',
    'wallet.history_empty': 'No hay movimientos registrados en tu cuenta.',
    'wallet.validation_multiple': 'Por favor, introduce un múltiplo de 500 DP.',
    'wallet.validation_insufficient': 'No tienes suficientes Dicipoints (DP).',
    'wallet.error_conversion': 'Error al procesar la conversión.',
    'wallet.recent': 'Reciente',
    'wallet.transaction': 'Transacción',

    // Reservations & Catalog
    'res.title': 'DiciCoin Smart Reservation',
    'res.subtitle': 'Gestiona tus reservas y explora el catálogo de monedas físicas disponibles.',
    'res.tab_my_plans': 'Mis Planes de Pago',
    'res.tab_catalog': 'Catálogo Disponible',
    'res.tab_faq': 'Preguntas Frecuentes (FAQ)',
    'res.no_active_plans': 'No tienes planes de pago activos',
    'res.no_active_plans_desc': 'Ve a la pestaña de "Catálogo Disponible" para reservar tu primera moneda.',
    'res.view_catalog': 'Ver Catálogo',
    'res.coin_physical': 'DiciCoin Física',
    'res.available_reserve': 'Disponible para reserva',
    'res.total_value': 'Valor total',
    'res.reserve_ten': 'Reserva (10%)',
    'res.btn_reserve': 'Reservar Moneda',
    'res.select_continent': 'Selecciona un Continente para explorar las monedas:',
    'res.grid_desc': 'Elige tu número de moneda favorito del 1 al 100 en la cuadrícula:',
    'res.status_available': 'Disponible',
    'res.status_reserved_other': 'Reservado por otro usuario',
    'res.status_reserved_me': 'Tu Reserva activa',
    'res.status_fully_paid': 'Moneda Pagada 100%',
    'res.status_payment_plan': 'En Plan de Pago',
    'res.cert_status_value': 'RESERVADO',
    'res.fully_paid_title': 'Propiedad Completa Garantizada',
    'res.fully_paid_desc': 'Has liquidado el 100% de esta moneda. Tienes derecho a la entrega física de la pieza y a la emisión del certificado digital de propiedad final. Ponte en contacto con soporte para la recogida.',
    'res.payment_history_title': 'Historial de cuotas abonadas',
    'res.installment_remaining': 'Saldo restante a liquidar:',
    'res.btn_pay': 'Pagar',
    'res.btn_pay_loading': 'Procesando...',
    'res.form_pay_installment': 'Realizar Pago Mensual / Parcial',

    // Legal modal and Shipping form
    'res.modal_title': 'Términos de Reserva y Envío Certificado',
    'res.modal_desc': 'Para completar tu preasignación y plan de envío de tu pieza de colección física, lee el acuerdo y rellena tus datos:',
    'res.form_name': 'Nombre Completo Titular',
    'res.form_email': 'Correo Electrónico de Contacto',
    'res.form_phone': 'Teléfono de Contacto (WhatsApp)',
    'res.form_country': 'País de Residencia',
    'res.form_city': 'Ciudad',
    'res.form_address': 'Dirección Completa de Envío Domiciliario',
    'res.legal_declaration': 'Declaro que entiendo que DiciCoin no es una inversión especulativa, que asumo voluntariamente la reserva del 10% (500 €) y el plan progresivo para completar el pago de la pieza, y que los datos declarados son correctos para el envío certificado a mi casa.',
    'res.btn_confirm': 'Confirmar Reserva e Inicializar Plan',
    'res.btn_confirm_loading': 'Procesando reserva...',
    'res.error_invalid_amount': 'Introduce un importe válido mayor a 0 €.',
    'res.error_reserve': 'Ocurrió un error al procesar la reserva.',
    'res.error_price_invalid': 'El precio debe ser mayor a 0 € y no exceder tu aportación total.',
    'res.error_publish_sale': 'Error al publicar la venta.',
    'res.error_invalid_shipping': 'Por favor, rellene todos los campos de envío obligatorios.',

    // Certificate
    'res.cert_title': 'Certificado Digital de Reserva',
    'res.cert_collectible': 'DICICOIN COLLECTIBLE',
    'res.cert_desc': 'Por el presente se hace constar que el titular de la cuenta DiciWallet posee los derechos exclusivos de reserva y preasignación sobre la pieza física:',
    'res.cert_verification_text': 'Con serial de acuñación único global verificado en el libro de actas digital de Dicilo.net.',
    'res.cert_status': 'ESTADO',
    'res.cert_continent': 'CONTINENTE',
    'res.cert_license': 'LICENCIA DIGITAL',
    'res.cert_owner_info': 'INFORMACIÓN DEL TITULAR',
    'res.cert_shipping_dest': 'DESTINO DE ENVÍO CERTIFICADO',
    'res.cert_footer': 'Este certificado digital acredita la posición del usuario en el plan de adquisición progresiva. Los derechos físicos definitivos se transferirán tras el pago del 100% del activo.',
    'res.cert_print': 'Imprimir Certificado',

    // FAQ Section
    'faq.title': 'Preguntas Frecuentes (FAQ) de DiciCoin',
    'faq.subtitle': 'Todo lo que necesitas saber sobre el ecosistema DiciCoin físico y digital.',
    'faq.q1': '¿Qué es DICICOIN?',
    'faq.a1': 'DICICOIN es una moneda física, conmemorativa y coleccionable creada como símbolo fundacional del ecosistema Dicilo. Representa pertenencia, visión a largo plazo y participación temprana en una plataforma internacional diseñada para conectar personas, empresas y oportunidades de forma transparente y responsable.<br /><br />DICICOIN no es una criptomoneda ni un instrumento financiero tradicional. Es un objeto físico de edición limitada que conecta el mundo tangible con el crecimiento del ecosistema digital Dicilo.',
    'faq.q2': '¿Para qué sirve DICICOIN?',
    'faq.a2': 'DICICOIN cumple varias funciones dentro del ecosistema Dicilo: actúa como pieza coleccionable de edición limitada, representa apoyo temprano al crecimiento de Dicilo, permite acceso preferente a procesos futuros definidos por la compañía, funciona como símbolo de pertenencia a la comunidad Dicilo y conecta al titular con la evolución estratégica de la plataforma. Cada DICICOIN es una decisión consciente de formar parte de un proyecto en construcción.',
    'faq.q3': '¿DICICOIN es una inversión financiera?',
    'faq.a3': 'No. DICICOIN no se comercializa como inversión, no promete rendimientos financieros ni garantiza beneficios económicos automáticos.<br /><br />Su valor principal es simbólico, estratégico y comunitario. En una etapa futura, cuando Dicilo alcance determinados hitos corporativos, legales y estructurales, las DICICOIN podrán habilitar procesos de conversión o canje bajo condiciones específicas definidas por la compañía y siempre dentro del marco legal correspondiente.',
    'faq.q4': '¿Cuál es el valor y el límite de adquisición de una DICICOIN?',
    'faq.a4': 'El valor de referencia actual de una DICICOIN es de 30 euros. Adicionalmente, cada moneda mantiene un valor base reconocido de 25 euros por unidad, considerado como referencia interna para futuros procesos habilitados por la compañía, siempre bajo los marcos legales correspondientes. Este valor no implica promesa de rentabilidad ni revalorización automática.<br /><br />Para garantizar una distribución equilibrada, transparente y responsable dentro de la comunidad, cada usuario puede adquirir un máximo de 2,000 DICICOIN.',
    'faq.q5': '¿Cuáles son las series y el formato de numeración por continente?',
    'faq.a5': 'La acuñación física está rígidamente limitada a un máximo de 2,000,000 monedas por continente (10,000,000 en total global) utilizando los siguientes prefijos oficiales y rangos de numeración:<br /><br />Europa (Prefijo EU-DC): EU-DC0000001 a EU-DC2000000<br />America (Prefijo LA-DC): LA-DC0000001 a LA-DC2000000<br />África (Prefijo AF-DC): AF-DC0000001 a AF-DC2000000<br />Asia (Prefijo AS-DC): AS-DC0000001 a AS-DC2000000<br />Oceanía (Prefijo OC-DC): OC-DC0000001 a OC-DC2000000<br /><br />Cada serial oficial es único, irrepetible y está vinculado a una licencia sellada y al titular registrado en dicilo.net.',
    'faq.q6': '¿Cómo puedo obtener una DICICOIN y por qué debo registrarme?',
    'faq.a6': 'Para adquirir una DICICOIN es obligatorio registrarse gratuitamente en la plataforma oficial dicilo.net, completar el registro como usuario verificado y realizar la compra exclusivamente a través de Agentes Autorizados de Venta. Las DICICOIN no se venden de forma anónima ni a través de canales no oficiales.<br /><br />El registro es necesario para verificar la identidad del titular, registrar la propiedad de cada moneda física, garantizar la trazabilidad y seguridad, descargar certificados oficiales y participar en futuros procesos del ecosistema.',

    // Marketplace
    'market.title': 'Marketplace de Participaciones',
    'market.subtitle': 'Compra derechos de reserva de monedas físicas a otros usuarios y asume su plan de pagos.',
    'market.how_works_title': '¿Cómo funciona?',
    'market.how_works_text': 'Cuando adquieres la participación de otro usuario, pagas su precio solicitado. Una vez aprobada la transferencia por el Administrador, se te transfiere el control de la reserva y el saldo que ya ha sido abonado. A partir de ahí, continúas pagando el saldo pendiente.',
    'market.no_listings': 'No hay participaciones listadas',
    'market.no_listings_desc': 'Actualmente ningún usuario ha puesto en venta su participación.',
    'market.seller_paid': 'Aportado por vendedor',
    'market.pending_assumed': 'Saldo pendiente asumido',
    'market.coin_total_value': 'Valor total de moneda',
    'market.own_listing': 'Es tu propia publicación',
    'market.btn_buy': 'Adquirir Participación',
    'market.confirm_buy': '¿Estás seguro de que deseas solicitar la compra de esta participación? La transacción estará sujeta a la aprobación manual de un administrador por seguridad.',
    'market.error_buy': 'Error al solicitar la compra.',
    'market.listing_tag': 'Participación en Venta',
    'market.transfer_id': 'ID Transferencia',

    // Admin
    'admin.title': 'Panel de Administración',
    'admin.subtitle': 'Gestión de la economía DiciCoin: dar de alta monedas y auditar transferencias.',
    'admin.pending_approvals': 'Aprobaciones de Transferencia Pendientes',
    'admin.no_pending': 'No hay solicitudes de transferencia en espera de aprobación.',
    'admin.seller': 'Vendedor',
    'admin.buyer': 'Comprador',
    'admin.paid_snapshot': 'Aportaciones abonadas',
    'admin.btn_approve': 'Aprobar',
    'admin.btn_reject': 'Rechazar',
    'admin.form_title': 'Dar de Alta Moneda Física',
    'admin.form_num_seq': 'Número Secuencial',
    'admin.form_preview': 'Previsualización del ID Oficial',
    'admin.form_preview_note': '* El serial digital único se generará automáticamente cuando un usuario la reserve.',
    'admin.form_btn_submit': 'Registrar en Catálogo',
    'admin.form_btn_submit_loading': 'Registrando...',
    'admin.inventory_title': 'Inventario General de Monedas',
    'admin.inv_coin_id': 'Moneda ID',
    'admin.inv_serial': 'Serial Digital (Licencia)',
    'admin.inv_continent': 'Continente',
    'admin.inv_status': 'Estado',
    'admin.inv_paid': 'Abonado',
    'admin.inv_owner': 'Propietario / Titular',
    'admin.inv_available': 'Sin reservar (Disponible)',
    'admin.inv_owner_none': 'Sin asignar (Disponible)',
    'admin.inventory_empty': 'No hay monedas físicas registradas en el sistema para este continente.',
    'admin.inventory_instructions': 'Seleccione de la lista el número del DiciCoin que le gustaría reservar.',
    'admin.click_to_populate': 'Haz clic para seleccionar este número',
    'admin.form_btn_reserve': 'Registrar Compra / Reservar',
    'admin.buyer_email': 'Email del Comprador',
    'admin.buyer_name': 'Nombre Completo',
    'admin.buyer_phone': 'Teléfono',
    'admin.buyer_country': 'País',
    'admin.buyer_city': 'Ciudad',
    'admin.buyer_address': 'Dirección',
    'admin.error_user_not_found': 'El usuario comprador no existe en el sistema. Debe registrarse primero.',
    'admin.error_coin_already_reserved': 'Esta moneda ya está reservada o tiene un plan de pagos activo.',
    'admin.success_reserve': 'Reserva y compra registrada con éxito para el usuario.',
    'admin.error_fill_all': 'Por favor, rellene todos los datos del comprador.',
    'admin.access_denied': 'Acceso Denegado',
    'admin.access_denied_desc': 'Esta sección es de uso exclusivo para los administradores del sistema DiciWallet.',
    'admin.error_invalid_number': 'Por favor, introduce un número secuencial válido (entre 1 y 2,000,000).',
    'admin.confirm_approve': '¿Estás seguro de que deseas aprobar esta transferencia de participación? Se transferirá el control de la reserva y se reajustarán los saldos.',
    'admin.confirm_reject': '¿Deseas rechazar esta transferencia? El comprador será eliminado y la moneda volverá a estar listada en venta.',
    'admin.error_register_coin': 'Error al registrar la moneda.',
    'admin.error_approve_transfer': 'Error al aprobar la transferencia.',
    'admin.error_reject_transfer': 'Error al rechazar la transferencia.',

    // Login
    'login.title': 'DICIWALLET',
    'login.subtitle': 'Ecosistema de Economía Circular Cerrada',
    'login.email': 'Correo Electrónico',
    'login.password': 'Contraseña',
    'login.btn_submit': 'Iniciar Sesión',
    'login.btn_submit_loading': 'Iniciando Sesión...',
    'login.no_account': '¿No tienes cuenta?',
    'login.register_here': 'Regístrate aquí',
    'login.legal_disclaimer': 'Al iniciar sesión, aceptas que DiciCoin es un activo coleccionable digital/físico de uso interno. No constituye una inversión garantizada ni se promete rentabilidad alguna.',
    'login.error_credentials': 'Credenciales incorrectas. Verifica tu email y contraseña.',
    'login.error_general': 'Ocurrió un error al intentar iniciar sesión. Reinténtalo.',

    // Register
    'register.title': 'DICIWALLET',
    'register.subtitle': 'Registro de Nuevo Usuario',
    'register.first_name': 'Nombre',
    'register.last_name': 'Apellidos',
    'register.email': 'Correo Electrónico',
    'register.password': 'Contraseña',
    'register.password_placeholder': 'Mínimo 6 caracteres',
    'register.btn_submit': 'Crear Cuenta',
    'register.btn_submit_loading': 'Registrando...',
    'register.has_account': '¿Ya tienes una cuenta?',
    'register.login_here': 'Inicia sesión',
    'register.legal_disclaimer': 'Al registrarte, confirmas que comprendes que DiciCoin no promete rentabilidad ni recompra garantizada, constituyendo un activo coleccionable del ecosistema Dicilo.',
    'register.error_length': 'La contraseña debe tener al menos 6 caracteres.',
    'register.error_email_in_use': 'El correo electrónico ya está registrado.',
    'register.error_general': 'Ocurrió un error al registrar el usuario. Reinténtalo.',

    // Continents
    'continent.EU': 'Europa',
    'continent.LA': 'America',
    'continent.AF': 'África',
    'continent.AS': 'Asia',
    'continent.OC': 'Oceanía',

    // Placeholders
    'login.email_placeholder': 'ejemplo@dicilo.net',
    'register.first_name_placeholder': 'Juan',
    'register.last_name_placeholder': 'Pérez',
    'register.email_placeholder': 'juan.perez@dicilo.net',

    // Server Actions
    'api.validation_multiple': 'La cantidad de DP debe ser un múltiplo de 500.',
    'api.error_no_wallet': 'No se encontró el monedero del usuario.',
    'api.validation_insufficient': 'Saldo insuficiente de Dicipoints (DP).',
    'api.conversion_success': 'Conversión completada con éxito.',
    'api.error_coin_not_found': 'La moneda especificada no existe.',
    'api.error_coin_unavailable': 'La moneda ya no está disponible para reserva o tiene dueño.',
    'api.error_wallet_not_found': 'El monedero del usuario no existe.',
    'api.success_reserve': 'Reserva completada con éxito.',
    'api.error_installment_exceeds': 'El pago excede el saldo pendiente.',
    'api.success_installment': 'Pago registrado correctamente.',
    'api.success_installment_completed': '¡Felicidades! Has completado el pago del 100% de tu DiciCoin.',
    'api.error_seller_mismatch': 'No eres el titular de esta reserva.',
    'api.error_status_not_active': 'Solo se pueden transferir reservas activas en plan de pago.',
    'api.error_price_invalid': 'El precio sugerido debe ser mayor a 0 € y no exceder lo que has pagado.',
    'api.success_listed': 'Tu participación ha sido listada en el Marketplace con éxito.',
    'api.error_not_listed': 'Esta participación ya no está en venta.',
    'api.error_self_buy': 'No puedes comprar tu propia participación.',
    'api.success_requested': 'Solicitud enviada. La transferencia está en espera de aprobación.',
    'api.server_error': 'Error en el servidor.',
    'api.admin.error_coin_exists': 'Ya existe una moneda con este identificador.',
    'api.admin.success_register_coin': 'Moneda física registrada correctamente.',
    'api.admin.error_transfer_not_found': 'La solicitud de transferencia no existe.',
    'api.admin.error_not_pending': 'La transferencia no está pendiente de aprobación.',
    'api.admin.error_no_buyer': 'No hay ningún comprador asignado a esta transferencia.',
    'api.admin.success_approve': 'Transferencia de participación aprobada y ejecutada correctamente.',
    'api.admin.success_reject': 'La solicitud de transferencia ha sido rechazada y la moneda vuelve a estar listada en el Marketplace.'
  },
  EN: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.wallet': 'My Wallet',
    'nav.reservations': 'DiciCoin Reservations',
    'nav.marketplace': 'Marketplace',
    'nav.admin': 'Administration',
    'nav.logout': 'Logout',
    'nav.member': 'Member',
    'nav.administrator': 'Administrator',

    // Common Balance widget
    'balance.dp': 'DP',
    'balance.dc': 'DC',
    'balance.paid': 'Paid',

    // Dashboard
    'dashboard.hello': 'Hello,',
    'dashboard.welcome': 'Welcome to the financial center of the DiciCoin circular ecosystem.',
    'dashboard.dp_title': 'Dicilo Activity Points',
    'dashboard.dp_desc': 'Accumulated through activity on Dicilo.net',
    'dashboard.dc_title': 'Digital DiciCoin',
    'dashboard.dc_desc': '1 DC = 50 EUR internal value',
    'dashboard.dc_convert': 'Convert DP',
    'dashboard.eur_title': 'Euros Paid',
    'dashboard.eur_desc': 'Total accumulated investment in physical coins',
    'dashboard.my_plans': 'My Physical Coins Payment Plan',
    'dashboard.no_plans': 'You do not have any active physical DiciCoin reservations.',
    'dashboard.no_plans_desc': 'You can reserve a collectible coin with a 10% down payment.',
    'dashboard.reserve_btn': 'Reserve Physical DiciCoin',
    'dashboard.progress_prop': 'Ownership progress',
    'dashboard.manage_payments': 'Manage Payments',
    'dashboard.remaining_prefix': 'Remaining',
    'dashboard.remaining_suffix': 'to get the physical certificate',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.action_reserve': 'Reserve New DiciCoin',
    'dashboard.action_convert': 'Convert DP to DC',
    'dashboard.action_market': 'Marketplace',
    'dashboard.legal_title': 'LEGAL AND RISK INFORMATION',
    'dashboard.legal_text': 'DiciCoin is a physical collectible asset, internal digital credit, premium access, and exclusive participation within the closed digital ecosystem Dicilo. Under no circumstances does it constitute a regulated or guaranteed financial investment. No future economic profitability, dividends, or mandatory buybacks are promised. Its value lies in the physical exclusivity and internal digital exchange utility on Dicilo.net.',

    // Wallet
    'wallet.title': 'My Digital Wallet',
    'wallet.subtitle': 'Convert your Dicilo.net points and review your transaction history.',
    'wallet.convert_card_title': 'Convert DP to DiciCoin',
    'wallet.rule_desc': 'Ecosystem Rule: 500 DP = 1 DC. Conversions are instant and reversible through official support. DiciCoins (DC) are valued at 50 internal EUR for purchases or benefit redemptions.',
    'wallet.input_label': 'DP Points to Convert',
    'wallet.available': 'Available',
    'wallet.placeholder': 'Multiples of 500 (e.g. 500, 1000)',
    'wallet.give': 'You Give',
    'wallet.receive': 'You Receive',
    'wallet.btn_submit': 'Convert to DiciCoin (DC)',
    'wallet.btn_submit_loading': 'Processing conversion...',
    'wallet.history_title': 'Transaction History',
    'wallet.history_empty': 'No transactions registered in your account.',
    'wallet.validation_multiple': 'Please enter a multiple of 500 DP.',
    'wallet.validation_insufficient': 'You do not have enough Dicipoints (DP).',
    'wallet.error_conversion': 'Error processing conversion.',
    'wallet.recent': 'Recent',
    'wallet.transaction': 'Transaction',

    // Reservations & Catalog
    'res.title': 'DiciCoin Smart Reservation',
    'res.subtitle': 'Manage your reservations and explore the catalog of available physical coins.',
    'res.tab_my_plans': 'My Payment Plans',
    'res.tab_catalog': 'Available Catalog',
    'res.tab_faq': 'Frequently Asked Questions (FAQ)',
    'res.no_active_plans': 'You do not have active payment plans',
    'res.no_active_plans_desc': 'Go to the "Available Catalog" tab to reserve your first coin.',
    'res.view_catalog': 'View Catalog',
    'res.coin_physical': 'Physical DiciCoin',
    'res.available_reserve': 'Available for reservation',
    'res.total_value': 'Total value',
    'res.reserve_ten': 'Reservation (10%)',
    'res.btn_reserve': 'Reserve Coin',
    'res.select_continent': 'Select a Continent to explore coins:',
    'res.grid_desc': 'Choose your favorite coin number from 1 to 100 in the grid:',
    'res.status_available': 'Available',
    'res.status_reserved_other': 'Reserved by another user',
    'res.status_reserved_me': 'Your Active Reservation',
    'res.status_fully_paid': 'Coin Fully Paid 100%',
    'res.status_payment_plan': 'In Payment Plan',
    'res.cert_status_value': 'RESERVED',
    'res.fully_paid_title': 'Guaranteed Full Ownership',
    'res.fully_paid_desc': 'You have paid 100% of this coin. You are entitled to the physical delivery of the piece and the issuance of the final digital ownership certificate. Contact support for collection.',
    'res.payment_history_title': 'History of paid installments',
    'res.installment_remaining': 'Remaining balance to pay:',
    'res.btn_pay': 'Pay',
    'res.btn_pay_loading': 'Processing...',
    'res.form_pay_installment': 'Make Monthly / Partial Payment',

    // Legal modal and Shipping form
    'res.modal_title': 'Reservation Terms and Certified Shipping',
    'res.modal_desc': 'To complete your pre-assignment and shipping plan for your physical collectible, read the agreement and fill in your details:',
    'res.form_name': 'Full Owner Name',
    'res.form_email': 'Contact Email Address',
    'res.form_phone': 'Contact Phone (WhatsApp)',
    'res.form_country': 'Country of Residence',
    'res.form_city': 'City',
    'res.form_address': 'Full Home Shipping Address',
    'res.legal_declaration': 'I declare that I understand DiciCoin is not a speculative investment, that I voluntarily assume the 10% reservation (€500) and the progressive plan to complete payment of the piece, and that the details provided are correct for certified shipping to my home.',
    'res.btn_confirm': 'Confirm Reservation & Initialize Plan',
    'res.btn_confirm_loading': 'Processing reservation...',
    'res.error_invalid_amount': 'Please enter a valid amount greater than 0 €.',
    'res.error_reserve': 'An error occurred while processing the reservation.',
    'res.error_price_invalid': 'The price must be greater than 0 € and not exceed your total contribution.',
    'res.error_publish_sale': 'Error publishing the sale.',
    'res.error_invalid_shipping': 'Please fill in all required shipping fields.',

    // Certificate
    'res.cert_title': 'Digital Reservation Certificate',
    'res.cert_collectible': 'DICICOIN COLLECTIBLE',
    'res.cert_desc': 'This is to certify that the holder of the DiciWallet account owns the exclusive reservation and pre-assignment rights for the physical piece:',
    'res.cert_verification_text': 'With a unique global minting serial verified in the digital records of Dicilo.net.',
    'res.cert_status': 'STATUS',
    'res.cert_continent': 'CONTINENT',
    'res.cert_license': 'DIGITAL LICENSE',
    'res.cert_owner_info': 'HOLDER INFORMATION',
    'res.cert_shipping_dest': 'CERTIFIED SHIPPING DESTINATION',
    'res.cert_footer': 'This digital certificate validates the user\'s position in the progressive acquisition plan. Final physical rights will be transferred after 100% of the asset value is paid.',
    'res.cert_print': 'Print Certificate',

    // FAQ Section
    'faq.title': 'DiciCoin Frequently Asked Questions (FAQ)',
    'faq.subtitle': 'Everything you need to know about the physical and digital DiciCoin ecosystem.',
    'faq.q1': 'What is DICICOIN?',
    'faq.a1': 'DICICOIN is a physical, commemorative, and collectible coin created as a founding symbol of the Dicilo ecosystem. It represents membership, long-term vision, and early participation in an international platform designed to connect people, companies, and opportunities transparently and responsibly.<br /><br />DICICOIN is not a cryptocurrency or a traditional financial instrument. It is a limited edition physical object that connects the tangible world with the growth of the Dicilo digital ecosystem.',
    'faq.q2': 'What is DICICOIN used for?',
    'faq.a2': 'DICICOIN serves several functions within the Dicilo ecosystem: it acts as a limited edition collectible piece, represents early support for the growth of Dicilo, allows preferential access to future processes defined by the company, serves as a symbol of belonging to the Dicilo community, and connects the holder with the strategic evolution of the platform. Each DICICOIN is a conscious decision to be part of a project under construction.',
    'faq.q3': 'Is DICICOIN a financial investment?',
    'faq.a3': 'No. DICICOIN is not marketed as an investment, does not promise financial returns, nor does it guarantee automatic economic benefits.<br /><br />Its primary value is symbolic, strategic, and community-based. In a future stage, when Dicilo reaches certain corporate, legal, and structural milestones, DICICOIN may enable conversion or redemption processes under specific conditions defined by the company and always within the corresponding legal framework.',
    'faq.q4': 'What is the value and limit of acquisition of a DICICOIN?',
    'faq.a4': 'The current reference value of a DICICOIN is 30 euros. Additionally, each coin maintains a recognized base value of 25 euros per unit, considered as an internal reference for future processes enabled by the company, always under the corresponding legal frameworks. This value does not imply any promise of profitability or automatic revaluation.<br /><br />To guarantee a balanced, transparent, and responsible distribution within the community, each user can purchase a maximum of 2,000 DICICOIN.',
    'faq.q5': 'What are the series and numbering format per continent?',
    'faq.a5': 'Physical minting is strictly limited to a maximum of 2,000,000 coins per continent (10,000,000 total globally) using the following official prefixes and numbering ranges:<br /><br />Europe (Prefix EU-DC): EU-DC0000001 to EU-DC2000000<br />America (Prefix LA-DC): LA-DC0000001 to LA-DC2000000<br />Africa (Prefix AF-DC): AF-DC0000001 to AF-DC2000000<br />Asia (Prefix AS-DC): AS-DC0000001 to AS-DC2000000<br />Oceania (Prefix OC-DC): OC-DC0000001 to OC-DC2000000<br /><br />Each official serial is unique, unrepeatable, and linked to a sealed license and the registered holder on dicilo.net.',
    'faq.q6': 'How can I obtain a DICICOIN and why must I register?',
    'faq.a6': 'To acquire a DICICOIN, it is mandatory to register for free on the official platform dicilo.net, complete the registration as a verified user, and make the purchase exclusively through Authorized Sales Agents. DICICOIN is not sold anonymously or through unofficial channels.<br /><br />Registration is necessary to verify the holder\'s identity, register the ownership of each physical coin, guarantee traceability and security, download official certificates, and participate in future ecosystem processes.',

    // Marketplace
    'market.title': 'Marketplace',
    'market.subtitle': 'Buy reservation rights for physical coins from other users and take over their payment plan.',
    'market.how_works_title': 'How does it work?',
    'market.how_works_text': 'When you acquire another user\'s participation, you pay their asking price. Once the transfer is approved by the Administrator, control of the reservation and the balance already paid is transferred to you. From there, you continue paying the pending balance.',
    'market.no_listings': 'No listings found',
    'market.no_listings_desc': 'Currently no user has listed their participation for sale.',
    'market.seller_paid': 'Seller contribution',
    'market.pending_assumed': 'Pending balance assumed',
    'market.coin_total_value': 'Total coin value',
    'market.own_listing': 'This is your own listing',
    'market.btn_buy': 'Acquire Participation',
    'market.confirm_buy': 'Are you sure you want to request to buy this participation? The transaction will be subject to manual approval by an administrator for security.',
    'market.error_buy': 'Error requesting purchase.',
    'market.listing_tag': 'Participation for Sale',
    'market.transfer_id': 'Transfer ID',

    // Admin
    'admin.title': 'Admin Panel',
    'admin.subtitle': 'DiciCoin economy management: register coins and audit participation transfers.',
    'admin.pending_approvals': 'Pending Transfer Approvals',
    'admin.no_pending': 'No transfer requests waiting for approval.',
    'admin.seller': 'Seller',
    'admin.buyer': 'Buyer',
    'admin.paid_snapshot': 'Paid contributions',
    'admin.btn_approve': 'Approve',
    'admin.btn_reject': 'Reject',
    'admin.form_title': 'Register Physical Coin',
    'admin.form_num_seq': 'Sequential Number',
    'admin.form_preview': 'Official ID Preview',
    'admin.form_preview_note': '* The unique digital serial will be generated automatically when a user reserves it.',
    'admin.form_btn_submit': 'Register in Catalog',
    'admin.form_btn_submit_loading': 'Registering...',
    'admin.inventory_title': 'General Coin Inventory',
    'admin.inv_coin_id': 'Coin ID',
    'admin.inv_serial': 'Digital Serial (License)',
    'admin.inv_continent': 'Continent',
    'admin.inv_status': 'Status',
    'admin.inv_paid': 'Paid Amount',
    'admin.inv_owner': 'Owner / Holder',
    'admin.inv_available': 'Not reserved (Available)',
    'admin.inv_owner_none': 'Unassigned (Available)',
    'admin.inventory_empty': 'No physical coins registered in the system for this continent.',
    'admin.inventory_instructions': 'Select from the list the DiciCoin number you would like to reserve.',
    'admin.click_to_populate': 'Click to select this number',
    'admin.form_btn_reserve': 'Register Purchase / Reserve',
    'admin.buyer_email': 'Buyer Email',
    'admin.buyer_name': 'Full Name',
    'admin.buyer_phone': 'Phone',
    'admin.buyer_country': 'Country',
    'admin.buyer_city': 'City',
    'admin.buyer_address': 'Address',
    'admin.error_user_not_found': 'The buyer user does not exist in the system. They must register first.',
    'admin.error_coin_already_reserved': 'This coin is already reserved or has an active payment plan.',
    'admin.success_reserve': 'Reservation and purchase registered successfully for the user.',
    'admin.error_fill_all': 'Please fill in all buyer details.',
    'admin.access_denied': 'Access Denied',
    'admin.access_denied_desc': 'This section is for the exclusive use of DiciWallet system administrators.',
    'admin.error_invalid_number': 'Please enter a valid sequential number (between 1 and 2,000,000).',
    'admin.confirm_approve': 'Are you sure you want to approve this participation transfer? Control of the reservation will be transferred and balances will be adjusted.',
    'admin.confirm_reject': 'Do you want to reject this transfer? The buyer will be removed and the coin will be listed for sale again.',
    'admin.error_register_coin': 'Error registering the coin.',
    'admin.error_approve_transfer': 'Error approving the transfer.',
    'admin.error_reject_transfer': 'Error rejecting the transfer.',

    // Login
    'login.title': 'DICIWALLET',
    'login.subtitle': 'Closed Circular Economy Ecosystem',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.btn_submit': 'Login',
    'login.btn_submit_loading': 'Logging in...',
    'login.no_account': 'Don\'t have an account?',
    'login.register_here': 'Register here',
    'login.legal_disclaimer': 'By logging in, you accept that DiciCoin is an internal digital/physical collectible asset. It does not constitute a guaranteed investment and no profitability is promised.',
    'login.error_credentials': 'Incorrect credentials. Please verify your email and password.',
    'login.error_general': 'An error occurred while logging in. Please try again.',

    // Register
    'register.title': 'DICIWALLET',
    'register.subtitle': 'New User Registration',
    'register.first_name': 'First Name',
    'register.last_name': 'Last Name',
    'register.email': 'Email Address',
    'register.password': 'Password',
    'register.password_placeholder': 'Minimum 6 characters',
    'register.btn_submit': 'Create Account',
    'register.btn_submit_loading': 'Registering...',
    'register.has_account': 'Already have an account?',
    'register.login_here': 'Log in',
    'register.legal_disclaimer': 'By registering, you confirm that you understand that DiciCoin does not promise profitability or guaranteed repurchase, constituting a collectible asset of the Dicilo ecosystem.',
    'register.error_length': 'Password must be at least 6 characters long.',
    'register.error_email_in_use': 'The email address is already registered.',
    'register.error_general': 'An error occurred during registration. Please try again.',

    // Continents
    'continent.EU': 'Europe',
    'continent.LA': 'America',
    'continent.AF': 'Africa',
    'continent.AS': 'Asia',
    'continent.OC': 'Oceania',

    // Placeholders
    'login.email_placeholder': 'example@dicilo.net',
    'register.first_name_placeholder': 'John',
    'register.last_name_placeholder': 'Doe',
    'register.email_placeholder': 'john.doe@dicilo.net',

    // Server Actions
    'api.validation_multiple': 'The amount of DP must be a multiple of 500.',
    'api.error_no_wallet': 'User wallet not found.',
    'api.validation_insufficient': 'Insufficient balance of Dicipoints (DP).',
    'api.conversion_success': 'Conversion completed successfully.',
    'api.error_coin_not_found': 'The specified coin does not exist.',
    'api.error_coin_unavailable': 'The coin is no longer available for reservation or has an owner.',
    'api.error_wallet_not_found': 'The user wallet does not exist.',
    'api.success_reserve': 'Reservation completed successfully.',
    'api.error_installment_exceeds': 'The payment exceeds the pending balance.',
    'api.success_installment': 'Payment registered successfully.',
    'api.success_installment_completed': 'Congratulations! You have completed 100% payment of your DiciCoin.',
    'api.error_seller_mismatch': 'You are not the holder of this reservation.',
    'api.error_status_not_active': 'Only active reservations on a payment plan can be transferred.',
    'api.error_price_invalid': 'The suggested price must be greater than 0 € and not exceed what you paid.',
    'api.success_listed': 'Your participation has been successfully listed in the Marketplace.',
    'api.error_not_listed': 'This participation is no longer for sale.',
    'api.error_self_buy': 'You cannot buy your own participation.',
    'api.success_requested': 'Request sent. The transfer is awaiting approval.',
    'api.server_error': 'Server error.',
    'api.admin.error_coin_exists': 'A coin with this identifier already exists.',
    'api.admin.success_register_coin': 'Physical coin registered successfully.',
    'api.admin.error_transfer_not_found': 'The transfer request does not exist.',
    'api.admin.error_not_pending': 'The transfer is not pending approval.',
    'api.admin.error_no_buyer': 'There is no buyer assigned to this transfer.',
    'api.admin.success_approve': 'Participation transfer approved and executed successfully.',
    'api.admin.success_reject': 'The transfer request has been rejected and the coin is listed on the Marketplace again.'
  },
  DE: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.wallet': 'Meine Wallet',
    'nav.reservations': 'DiciCoin-Reservierungen',
    'nav.marketplace': 'Marktplatz',
    'nav.admin': 'Verwaltung',
    'nav.logout': 'Abmelden',
    'nav.member': 'Mitglied',
    'nav.administrator': 'Administrator',

    // Common Balance widget
    'balance.dp': 'DP',
    'balance.dc': 'DC',
    'balance.paid': 'Bezahlt',

    // Dashboard
    'dashboard.hello': 'Hallo,',
    'dashboard.welcome': 'Willkommen im Finanzzentrum des zirkulären DiciCoin-Ökosystems.',
    'dashboard.dp_title': 'Dicilo Aktivitätspunkte',
    'dashboard.dp_desc': 'Gesammelt durch Aktivitäten auf Dicilo.net',
    'dashboard.dc_title': 'Digitale DiciCoin',
    'dashboard.dc_desc': '1 DC = 50 EUR interner Wert',
    'dashboard.dc_convert': 'DP umrechnen',
    'dashboard.eur_title': 'Bezahlte Euros',
    'dashboard.eur_desc': 'Kumulierte Gesamtinvestition in physische Münzen',
    'dashboard.my_plans': 'Mein Zahlungsplan für physische Münzen',
    'dashboard.no_plans': 'Sie haben keine aktiven physischen DiciCoin-Reservierungen.',
    'dashboard.no_plans_desc': 'Sie können eine Sammlermünze mit einer Anzahlung von 10% reservieren.',
    'dashboard.reserve_btn': 'Physische DiciCoin reservieren',
    'dashboard.progress_prop': 'Eigentumsfortschritt',
    'dashboard.manage_payments': 'Zahlungen verwalten',
    'dashboard.remaining_prefix': 'Noch',
    'dashboard.remaining_suffix': 'erforderlich, um das physische Zertifikat zu erhalten',
    'dashboard.quick_actions': 'Schnellzugriff',
    'dashboard.action_reserve': 'Neue DiciCoin reservieren',
    'dashboard.action_convert': 'DP in DC umrechnen',
    'dashboard.action_market': 'Marktplatz',
    'dashboard.legal_title': 'RECHTLICHE HINWEISE UND RISIKOINFORMATIONEN',
    'dashboard.legal_text': 'DiciCoin is ein physisches Sammlerstück, ein internes digitales Guthaben, ein Premium-Zugang und eine exklusive Beteiligung innerhalb des geschlossenen digitalen Ökosystems Dicilo. Es stellt unter keinen Umständen eine regulierte oder garantierte Finanzinvestition dar. Es wird keine zukünftige wirtschaftliche Rentabilität, Dividenden oder eine obligatorische Rückkaufverpflichtung versprochen. Sein Wert liegt in der physischen Exklusivität und dem internen digitalen Nutzen auf Dicilo.net.',

    // Wallet
    'wallet.title': 'Meine digitale Wallet',
    'wallet.subtitle': 'Rechnen Sie Ihre Dicilo.net-Punkte um und überprüfen Sie Ihren Transaktionsverlauf.',
    'wallet.convert_card_title': 'DP in DiciCoin umrechnen',
    'wallet.rule_desc': 'Ökosystem-Regel: 500 DP = 1 DC. Die Umrechnung erfolgt sofort und ist über den offiziellen Support umkehrbar. DiciCoins (DC) haben einen internen Wert von 50 EUR für Einkäufe oder das Einlösen von Vorteilen.',
    'wallet.input_label': 'Umzurechnende DP-Punkte',
    'wallet.available': 'Verfügbar',
    'wallet.placeholder': 'Vielfache von 500 (z.B. 500, 1000)',
    'wallet.give': 'Sie geben',
    'wallet.receive': 'Sie erhalten',
    'wallet.btn_submit': 'In DiciCoin (DC) umrechnen',
    'wallet.btn_submit_loading': 'Umrechnung wird verarbeitet...',
    'wallet.history_title': 'Transaktionsverlauf',
    'wallet.history_empty': 'Keine Transaktionen in Ihrem Konto registriert.',
    'wallet.validation_multiple': 'Bitte geben Sie ein Vielfaches von 500 DP ein.',
    'wallet.validation_insufficient': 'Sie haben nicht genügend Dicipoints (DP).',
    'wallet.error_conversion': 'Fehler beim Verarbeiten der Konvertierung.',
    'wallet.recent': 'Kürzlich',
    'wallet.transaction': 'Transaktion',

    // Reservations & Catalog
    'res.title': 'DiciCoin Smart-Reservierung',
    'res.subtitle': 'Verwalten Sie Ihre Reservierungen und erkunden Sie den Katalog der verfügbaren physischen Münzen.',
    'res.tab_my_plans': 'Meine Zahlungspläne',
    'res.tab_catalog': 'Verfügbarer Katalog',
    'res.tab_faq': 'Häufig gestellte Fragen (FAQ)',
    'res.no_active_plans': 'Sie haben keine aktiven Zahlungspläne',
    'res.no_active_plans_desc': 'Gehen Sie auf die Registerkarte "Verfügbarer Katalog", um Ihre erste Münze zu reservieren.',
    'res.view_catalog': 'Katalog anzeigen',
    'res.coin_physical': 'Physische DiciCoin',
    'res.available_reserve': 'Zur Reservierung verfügbar',
    'res.total_value': 'Gesamtwert',
    'res.reserve_ten': 'Reservierung (10%)',
    'res.btn_reserve': 'Münze reservieren',
    'res.select_continent': 'Wählen Sie einen Kontinent aus, um Münzen anzuzeigen:',
    'res.grid_desc': 'Wählen Sie Ihre bevorzugte Münznummer von 1 bis 100 im Raster:',
    'res.status_available': 'Verfügbar',
    'res.status_reserved_other': 'Von anderem Benutzer reserviert',
    'res.status_reserved_me': 'Ihre aktive Reservierung',
    'res.status_fully_paid': 'Münze zu 100% bezahlt',
    'res.status_payment_plan': 'Im Zahlungsplan',
    'res.cert_status_value': 'RESERVIERT',
    'res.fully_paid_title': 'Garantiertes volles Eigentum',
    'res.fully_paid_desc': 'Sie haben 100 % dieser Münze bezahlt. Sie haben Anspruch auf die physische Lieferung der Münze und die Ausstellung der endgültigen digitalen Eigentumsurkunde. Wenden Sie sich zur Abholung an den Support.',
    'res.payment_history_title': 'Verlauf der bezahlten Raten',
    'res.installment_remaining': 'Verbleibender Restbetrag:',
    'res.btn_pay': 'Bezahlen',
    'res.btn_pay_loading': 'Wird verarbeitet...',
    'res.form_pay_installment': 'Monatliche / Teilzahlung leisten',

    // Legal modal and Shipping form
    'res.modal_title': 'Reservierungsbedingungen und zertifizierter Versand',
    'res.modal_desc': 'Um Ihre Vorreservierung und Ihren Versandplan für Ihr physisches Sammlerstück abzuschließen, lesen Sie die Vereinbarung und tragen Sie Ihre Daten ein:',
    'res.form_name': 'Vollständiger Name des Inhabers',
    'res.form_email': 'Kontakt-E-Mail-Adresse',
    'res.form_phone': 'Kontakttelefon (WhatsApp)',
    'res.form_country': 'Wohnsitzland',
    'res.form_city': 'Stadt',
    'res.form_address': 'Vollständige Versandadresse zu Hause',
    'res.legal_declaration': 'Ich erkläre, dass ich verstehe, dass DiciCoin keine spekulative Investition ist, dass ich freiwillig die Reservierung von 10% (500 €) und den schrittweisen Plan zur vollständigen Bezahlung der Münze übernehme und dass die gemachten Angaben für den zertifizierten Versand zu mir nach Hause korrekt sind.',
    'res.btn_confirm': 'Reservierung bestätigen & Plan starten',
    'res.btn_confirm_loading': 'Reservierung wird verarbeitet...',
    'res.error_invalid_amount': 'Bitte geben Sie einen gültigen Betrag größer als 0 € ein.',
    'res.error_reserve': 'Bei der Verarbeitung der Reservierung ist ein Fehler aufgetreten.',
    'res.error_price_invalid': 'Der Preis muss größer als 0 € sein und darf Ihren Gesamtbeitrag nicht überschreiten.',
    'res.error_publish_sale': 'Fehler beim Veröffentlichen des Verkaufs.',
    'res.error_invalid_shipping': 'Bitte füllen Sie alle erforderlichen Versandfelder aus.',

    // Certificate
    'res.cert_title': 'Digitales Reservierungszertifikat',
    'res.cert_collectible': 'DICICOIN COLLECTIBLE',
    'res.cert_desc': 'Hiermit wird bescheinigt, dass der Inhaber des DiciWallet-Kontos die exklusiven Reservierungs- und Vorzuweisungsrechte für das physische Stück besitzt:',
    'res.cert_verification_text': 'Mit einer weltweit eindeutigen Prägungsseriennummer, die in den digitalen Protokollen von Dicilo.net verifiziert ist.',
    'res.cert_status': 'STATUS',
    'res.cert_continent': 'KONTINENT',
    'res.cert_license': 'DIGITALE LIZENZ',
    'res.cert_owner_info': 'INHABER-INFORMATIONEN',
    'res.cert_shipping_dest': 'ZERTIFIZIERTES VERSANDZIEL',
    'res.cert_footer': 'Dieses digitale Zertifikat bestätigt die Position des Benutzers im schrittweisen Erwerbsplan. Die endgültigen physischen Rechte werden nach der Zahlung von 100% des Vermögenswerts übertragen.',
    'res.cert_print': 'Zertifikat drucker',

    // FAQ Section
    'faq.title': 'DiciCoin Häufig gestellte Fragen (FAQ)',
    'faq.subtitle': 'Alles, was Sie über das physische und digitale DiciCoin-Ökosystem wissen müssen.',
    'faq.q1': 'Was ist DICICOIN?',
    'faq.a1': 'DICICOIN ist eine physische Gedenk- und Sammlermünze, die als Gründungssymbol des Dicilo-Ökosystems geschaffen wurde. Sie repräsentiert Zugehörigkeit, langfristige Vision und frühe Beteiligung an einer internationalen Plattform, die darauf ausgelegt ist, Menschen, Unternehmen und Chancen transparent und verantwortungsbewusst zu verbinden.<br /><br />DICICOIN ist keine Kryptowährung und kein traditionelles Finanzinstrument. Es ist ein physisches Objekt in limitierter Auflage, das die greifbare Welt mit dem Wachstum des digitalen Dicilo-Ökosystems verbindet.',
    'faq.q2': 'Wofür wird DICICOIN verwendet?',
    'faq.a2': 'DICICOIN erfüllt mehrere Funktionen innerhalb des Dicilo-Ökosystems: Sie fungiert als Sammlerstück in limitierter Auflage, repräsentiert die frühe Unterstützung für das Wachstum von Dicilo, ermöglicht bevorzugten Zugang zu zukünftigen, vom Unternehmen definierten Prozessen, dient als Symbol der Zugehörigkeit zur Dicilo-Gemeinschaft und verbindet den Inhaber mit der strategischen Entwicklung der Plattform. Jede DICICOIN ist eine bewusste Entscheidung, Teil eines im Bau befindlichen Projekts zu sein.',
    'faq.q3': 'Ist DICICOIN eine Finanzinvestition?',
    'faq.a3': 'Nein. DICICOIN wird nicht als Investition vermarktet, verspricht keine finanziellen Renditen und garantiert keine automatischen wirtschaftlichen Vorteile.<br /><br />Ihr Hauptwert ist symbolischer, strategischer und gemeinschaftlicher Natur. In einer zukünftigen Phase, wenn Dicilo bestimmte unternehmerische, rechtliche und strukturelle Meilensteine erreicht, können DICICOIN Umwandlungs- oder Einlösungsprozesse unter bestimmten, vom Unternehmen definierten Bedingungen und stets im entsprechenden rechtlichen Rahmen ermöglichen.',
    'faq.q4': 'Was ist der Wert und das Erwerbslimit einer DICICOIN?',
    'faq.a4': 'Der aktuelle Referenzwert einer DICICOIN beträgt 30 Euro. Darüber hinaus behält jede Münze einen anerkannten Basiswert von 25 Euro pro Einheit bei, der als interne Referenz für zukünftige, vom Unternehmen freigegebene Prozesse gilt, stets im Rahmen der entsprechenden gesetzlichen Bestimmungen. Dieser Wert impliziert kein Versprechen auf Rentabilität oder automatische Aufwertung.<br /><br />Um eine ausgewogene, transparente und verantwortungsvolle Verteilung in der Gemeinschaft zu gewährleisten, kann jeder Benutzer maximal 2.000 DICICOIN erwerben.',
    'faq.q5': 'Welche Serien und Nummerierungsformate gibt es pro Kontinent?',
    'faq.a5': 'Die physische Prägung ist streng auf maximal 2,000,000 Münzen pro Kontinent (10,000,000 insgesamt weltweit) begrenzt, unter Verwendung der folgenden offiziellen Präfixe und Nummerierungsbereiche:<br /><br />Europa (Präfix EU-DC): EU-DC0000001 bis EU-DC2000000<br />America (Präfix LA-DC): LA-DC0000001 bis LA-DC2000000<br />Afrika (Präfix AF-DC): AF-DC0000001 bis AF-DC2000000<br />Asien (Präfix AS-DC): AS-DC0000001 bis AS-DC2000000<br />Ozeanien (Präfix OC-DC): OC-DC0000001 bis OC-DC2000000<br /><br />Jede offizielle Seriennummer ist einzigartig, unwiederholbar und mit einer versiegelten Lizenz und dem auf dicilo.net registrierten Inhaber verknüpft.',
    'faq.q6': 'Wie kann ich eine DICICOIN erwerben und warum muss ich mich registrieren?',
    'faq.a6': 'Um eine DICICOIN zu erwerben, ist es zwingend erforderlich, sich kostenlos auf der offiziellen Plattform dicilo.net zu registrieren, die Registrierung als verifizierter Benutzer abzuschließen und den Kauf ausschließlich über autorisierte Verkaufsstellen abzuwickeln. DICICOIN werden nicht anonym oder über inoffizielle Kanäle verkauft.<br /><br />Die Registrierung ist erforderlich, um die Identität des Inhabers zu überprüfen, das Eigentum an jeder physischen Münze zu registrieren, Rückverfolgbarkeit und Sicherheit zu gewährleisten, offizielle Zertifikate herunterzuladen und an zukünftigen Prozessen des Ökosystems teilzunehmen.',

    // Marketplace
    'market.title': 'Marktplatz',
    'market.subtitle': 'Kaufen Sie Reservierungsrechte für physische Münzen von anderen Benutzern und übernehmen Sie deren Zahlungsplan.',
    'market.how_works_title': 'Wie funktioniert es?',
    'market.how_works_text': 'Wenn Sie die Beteiligung eines anderen Benutzers erwerben, zahlen Sie dessen geforderten Preis. Sobald die Übertragung vom Administrator genehmigt wurde, wird die Kontrolle über die Reservierung und das bereits bezahlte Guthaben auf Sie übertragen. Von dort aus zahlen Sie das ausstehende Guthaben weiter ab.',
    'market.no_listings': 'Keine Angebote gefunden',
    'market.no_listings_desc': 'Derzeit hat kein Benutzer seine Beteiligung zum Verkauf angeboten.',
    'market.seller_paid': 'Verkäufer-Beitrag',
    'market.pending_assumed': 'Ausstehender Restbetrag übernommen',
    'market.coin_total_value': 'Gesamtwert der Münze',
    'market.own_listing': 'Dies ist Ihr eigenes Angebot',
    'market.btn_buy': 'Beteiligung erwerben',
    'market.confirm_buy': 'Sind Sie sicher, dass Sie den Kauf dieser Beteiligung beantragen möchten? Die Transaktion unterliegt aus Sicherheitsgründen der manuellen Genehmigung durch einen Administrator.',
    'market.error_buy': 'Fehler beim Anfordern des Kaufs.',
    'market.listing_tag': 'Beteiligung zum Verkauf',
    'market.transfer_id': 'Übertragungs-ID',

    // Admin
    'admin.title': 'Verwaltungskonsole',
    'admin.subtitle': 'Verwaltung der DiciCoin-Wirtschaft: Registrierung von Münzen und Prüfung von Beteiligungsübertragungen.',
    'admin.pending_approvals': 'Ausstehende Übertragungsanträge',
    'admin.no_pending': 'Keine Übertragungsanträge warten auf Genehmigung.',
    'admin.seller': 'Verkäufer',
    'admin.buyer': 'Käufer',
    'admin.paid_snapshot': 'Eingezahlte Beiträge',
    'admin.btn_approve': 'Genehmigen',
    'admin.btn_reject': 'Ablehnen',
    'admin.form_title': 'Physische Münze registrieren',
    'admin.form_num_seq': 'Sequenznummer',
    'admin.form_preview': 'Vorschau der offiziellen ID',
    'admin.form_preview_note': '* Die eindeutige digitale Seriennummer wird automatisch generiert, wenn ein Benutzer sie reserviert.',
    'admin.form_btn_submit': 'Im Katalog registrieren',
    'admin.form_btn_submit_loading': 'Wird registriert...',
    'admin.inventory_title': 'Münzinventar',
    'admin.inv_coin_id': 'Münze ID',
    'admin.inv_serial': 'Digitale Seriennummer (Lizenz)',
    'admin.inv_continent': 'Kontinent',
    'admin.inv_status': 'Status',
    'admin.inv_paid': 'Bezahlter Betrag',
    'admin.inv_owner': 'Eigentümer / Inhaber',
    'admin.inv_available': 'Nicht reserviert (Verfügbar)',
    'admin.inv_owner_none': 'Nicht zugewiesen (Verfügbar)',
    'admin.inventory_empty': 'Für diesen Kontinent sind keine physischen Münzen im System registriert.',
    'admin.inventory_instructions': 'Wählen Sie aus der Liste die DiciCoin-Nummer aus, die Sie reservieren möchten.',
    'admin.click_to_populate': 'Klicken Sie hier, um diese Nummer auszuwählen',
    'admin.form_btn_reserve': 'Kauf registrieren / Reservieren',
    'admin.buyer_email': 'E-Mail des Käufers',
    'admin.buyer_name': 'Vollständiger Name',
    'admin.buyer_phone': 'Telefon',
    'admin.buyer_country': 'Land',
    'admin.buyer_city': 'Stadt',
    'admin.buyer_address': 'Adresse',
    'admin.error_user_not_found': 'Der Käufer existiert nicht im System. Er muss sich zuerst registrieren.',
    'admin.error_coin_already_reserved': 'Diese Münze ist bereits reserviert oder hat einen aktiven Zahlungsplan.',
    'admin.success_reserve': 'Reservierung und Kauf erfolgreich für den Benutzer registriert.',
    'admin.error_fill_all': 'Bitte füllen Sie alle Angaben zum Käufer aus.',
    'admin.access_denied': 'Zugriff verweigert',
    'admin.access_denied_desc': 'Dieser Bereich ist der exklusiven Nutzung durch DiciWallet-Systemadministratoren vorbehalten.',
    'admin.error_invalid_number': 'Bitte geben Sie eine gültige Sequenznummer ein (zwischen 1 und 2.000.000).',
    'admin.confirm_approve': 'Sind Sie sicher, dass Sie diese Beteiligungsübertragung genehmigen möchten? Die Transaktion unterliegt aus Sicherheitsgründen der manuellen Genehmigung durch einen Administrator.',
    'admin.confirm_reject': 'Möchten Sie diese Übertragung ablehnen? Der Käufer wird entfernt und die Münze wird wieder zum Verkauf angeboten.',
    'admin.error_register_coin': 'Fehler beim Registrieren der Münze.',
    'admin.error_approve_transfer': 'Fehler beim Genehmigen der Übertragung.',
    'admin.error_reject_transfer': 'Fehler beim Ablehnen der Übertragung.',

    // Login
    'login.title': 'DICIWALLET',
    'login.subtitle': 'Geschlossenes Kreislaufwirtschafts-Ökosystem',
    'login.email': 'E-Mail-Adresse',
    'login.password': 'Passwort',
    'login.btn_submit': 'Einloggen',
    'login.btn_submit_loading': 'Anmeldung...',
    'login.no_account': 'Sie haben noch kein Konto?',
    'login.register_here': 'Hier registrieren',
    'login.legal_disclaimer': 'Mit der Anmeldung akzeptieren Sie, dass DiciCoin ein internes digitales/physisches Sammlerstück ist. Es stellt keine garantierte Investition dar und es wird keine Rentabilität versprochen.',
    'login.error_credentials': 'Ungültige Anmeldedaten. Bitte überprüfen Sie Ihre E-Mail-Adresse und Ihr Passwort.',
    'login.error_general': 'Ein Fehler ist bei der Anmeldung aufgetreten. Bitte versuchen Sie es erneut.',

    // Register
    'register.title': 'DICIWALLET',
    'register.subtitle': 'Registrierung neuer Benutzer',
    'register.first_name': 'Vorname',
    'register.last_name': 'Nachname',
    'register.email': 'E-Mail-Adresse',
    'register.password': 'Passwort',
    'register.password_placeholder': 'Mindestens 6 Zeichen',
    'register.btn_submit': 'Konto erstellen',
    'register.btn_submit_loading': 'Registrierung...',
    'register.has_account': 'Haben Sie bereits ein Konto?',
    'register.login_here': 'Einloggen',
    'register.legal_disclaimer': 'Mit der Registrierung bestätigen Sie, dass Sie verstehen, dass DiciCoin keine Rentabilität oder einen garantierten Rückkauf verspricht, sondern ein Sammlerstück des Dicilo-Ökosystems darstellt.',
    'register.error_length': 'Das Passwort muss mindestens 6 Zeichen lang sein.',
    'register.error_email_in_use': 'Die E-Mail-Adresse ist bereits registriert.',
    'register.error_general': 'Ein Fehler ist bei der Registrierung aufgetreten. Bitte versuchen Sie es erneut.',

    // Continents
    'continent.EU': 'Europa',
    'continent.LA': 'America',
    'continent.AF': 'Afrika',
    'continent.AS': 'Asien',
    'continent.OC': 'Ozeanien',

    // Placeholders
    'login.email_placeholder': 'beispiel@dicilo.net',
    'register.first_name_placeholder': 'Max',
    'register.last_name_placeholder': 'Mustermann',
    'register.email_placeholder': 'max.mustermann@dicilo.net',

    // Server Actions
    'api.validation_multiple': 'Die Anzahl der DP muss ein Vielfaches von 500 sein.',
    'api.error_no_wallet': 'Benutzer-Wallet nicht gefunden.',
    'api.validation_insufficient': 'Ungenügendes Guthaben an Dicipoints (DP).',
    'api.conversion_success': 'Konvertierung erfolgreich abgeschlossen.',
    'api.error_coin_not_found': 'Die angegebene Münze existiert nicht.',
    'api.error_coin_unavailable': 'Die Münze ist nicht mehr zur Reservierung verfügbar oder hat einen Besitzer.',
    'api.error_wallet_not_found': 'Das Benutzer-Wallet existiert nicht.',
    'api.success_reserve': 'Reservierung erfolgreich abgeschlossen.',
    'api.error_installment_exceeds': 'Die Zahlung überschreitet den ausstehenden Restbetrag.',
    'api.success_installment': 'Zahlung erfolgreich registriert.',
    'api.success_installment_completed': 'Herzlichen Glückwunsch! Sie haben die Zahlung Ihrer DiciCoin zu 100% abgeschlossen.',
    'api.error_seller_mismatch': 'Sie sind nicht der Inhaber dieser Reservierung.',
    'api.error_status_not_active': 'Nur aktive Reservierungen im Zahlungsplan können übertragen werden.',
    'api.error_price_invalid': 'Der vorgeschlagene Preis muss größer als 0 € sein und darf den von Ihnen bezahlten Betrag nicht überschreiten.',
    'api.success_listed': 'Ihre Beteiligung wurde erfolgreich im Marktplatz gelistet.',
    'api.error_not_listed': 'Diese Beteiligung steht nicht mehr zum Verkauf.',
    'api.error_self_buy': 'Sie können Ihre eigene Beteiligung nicht kaufen.',
    'api.success_requested': 'Anfrage gesendet. Die Übertragung wartet auf Genehmigung.',
    'api.server_error': 'Serverfehler.',
    'api.admin.error_coin_exists': 'Eine Münze mit dieser Kennung existiert bereits.',
    'api.admin.success_register_coin': 'Physische Münze erfolgreich registriert.',
    'api.admin.error_transfer_not_found': 'Der Übertragungsantrag existiert nicht.',
    'api.admin.error_not_pending': 'Die Übertragung wartet nicht auf Genehmigung.',
    'api.admin.error_no_buyer': 'Dieser Übertragung ist kein Käufer zugeordnet.',
    'api.admin.success_approve': 'Beteiligungsübertragung erfolgreich genehmigt und ausgeführt.',
    'api.admin.success_reject': 'Der Übertragungsantrag wurde abgelehnt und die Münze ist wieder auf dem Marktplatz gelistet.'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ES');

  // Cargar preferencia del localStorage si existe
  useEffect(() => {
    const saved = localStorage.getItem('diciwallet_lang') as Language;
    if (saved && (saved === 'ES' || saved === 'EN' || saved === 'DE')) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('diciwallet_lang', lang);
  };

  const t = (key: string): string => {
    return dictionary[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
