'use server';

import { getAdminDb } from '@/lib/firebase-admin';
import * as admin from 'firebase-admin';

// Helper to normalize strings for comparison (e.g., "St. Pauli" -> "stpauli")
function normalize(str: string) {
    return str.toLowerCase().replace(/[^a-z0-9]/g, '');
}

export async function registerNeighborhood(neighborhoodName: string, userId: string) {
    if (!neighborhoodName || !neighborhoodName.trim()) {
        return { success: false, error: "El nombre del barrio es obligatorio." };
    }

    const db = getAdminDb();
    const cleanName = neighborhoodName.trim();
    const normalizedName = normalize(cleanName);

    try {
        // --- PASO A: Verificación Interna (Firestore) ---
        // Check if explicitly exists in 'neighborhoods' collection
        // We assume the ID is the normalized name or we query by a field 'normalizedName'
        const neighborhoodsRef = db.collection('neighborhoods');
        const q = neighborhoodsRef.where('normalizedName', '==', normalizedName).limit(1);
        const snapshot = await q.get();

        if (!snapshot.empty) {
            // Already exists
            const existing = snapshot.docs[0].data();
            return {
                success: true,
                exists: true,
                slug: existing.slug || existing.id || displayToSlug(existing.name),
                message: "¡Este barrio ya existe!"
            };
        }

        // --- PASO B: Verificación Externa (Google Places API) ---
        const googleApiKey = process.env.GOOGLE_MAPS_API_KEY || process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
        if (!googleApiKey) {
            console.error("Missing GOOGLE_MAPS_API_KEY");
            return { success: false, error: "Error de configuración del sistema (API Key)." };
        }

        // https://developers.google.com/maps/documentation/places/web-service/search-text
        const searchUrl = `https://maps.googleapis.com/maps/api/place/textsearch/json?query=${encodeURIComponent(cleanName)}&key=${googleApiKey}`;

        const googleRes = await fetch(searchUrl);
        const googleData = await googleRes.json();

        if (googleData.status !== 'OK' && googleData.status !== 'ZERO_RESULTS') {
            console.error("Google Places API Error:", googleData);
            return { success: false, error: "Error al verificar con Google Maps." };
        }

        // Filter for valid types
        const validTypes = ['neighborhood', 'sublocality', 'political', 'sublocality_level_1'];
        const validPlace = googleData.results?.find((place: any) =>
            place.types.some((t: string) => validTypes.includes(t))
        );

        if (!validPlace) {
            return {
                success: false,
                error: "No hemos podido verificar que este barrio exista realmente. Por favor revisa el nombre."
            };
        }

        // --- PASO C: Auto-Creación (Auto-Approval) ---
        const officialName = validPlace.name;
        const location = validPlace.geometry?.location || { lat: 0, lng: 0 };
        const newSlug = displayToSlug(officialName);

        const newDocRef = neighborhoodsRef.doc(newSlug); // Use slug as ID for cleaner URLs

        await newDocRef.set({
            name: officialName,
            slug: newSlug,
            normalizedName: normalize(officialName),
            city: parseCityFromAddress(validPlace.formatted_address) || 'Unknown', // Helper needed
            location: location,
            placeId: validPlace.place_id,
            createdBy: userId,
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
            status: 'active', // Auto-approved
            isAutoGenerated: true
        });

        return {
            success: true,
            created: true,
            slug: newSlug,
            name: officialName,
            message: "¡Barrio verificado y creado!"
        };

    } catch (error: any) {
        console.error("Error registering neighborhood:", error);
        return { success: false, error: "Error interno del servidor." };
    }
}

function displayToSlug(text: string) {
    return text
        .toLowerCase()
        .replace(/[^\w ]+/g, '')
        .replace(/ +/g, '-');
}

function parseCityFromAddress(address: string): string {
    // Basic heuristics for City. Google Address Components would be better but require details fetch
    // Ensure we default to something reasonable if not found.
    // Address format usually: "Neighborhood, City, Country" or "Neighborhood, City"
    if (!address) return '';
    const parts = address.split(',');
    if (parts.length >= 2) {
        // Return the second to last p art usually contains city/zip
        // This is fuzzy. For "Hamburg", usually simply "Hamburg" works.
        // Let's rely on basic string check or return the input as fallback
        if (address.includes('Hamburg')) return 'Hamburg';
        if (address.includes('Berlin')) return 'Berlin';
        return parts[parts.length - 2].trim().replace(/[0-9]/g, '').trim(); // Remove zip codes
    }
    return 'Hamburg'; // Default fallback as per user context predominant city
}
